version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - .:/code
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
